### PR TITLE
Add the x86 rootfs to the cross image

### PR DESCRIPTION
**Pull request by jashook**
This will be used to build x86_arm crossgen.

### CODE REVIEW

**Comment by jashook** [comment]
@MichaelSimons @RussKeldorph @echesakovMSFT PTAL

**Comment by echesakovMSFT** [comment]
@jashook LGTM

**Comment by MichaelSimons** [comment]
@dotnet-bot test centos_6 please

**Comment by MichaelSimons** [comment]
centos_6 CI failure is not related to the changed Dockerfile - logged https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/19.

**Comment by MichaelSimons** [comment]
The images produced from this PR are the following:

microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-4929dd6-20180301213238
microsoft/dotnet-buildtools-prereqs:ubuntu-14.04
microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-debpkg-d770b8b-20180301213238
microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-coredeps-d770b8b-20180301213238
microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-coredeps
microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-crossdeps-d770b8b-20180301213238
microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-crossdeps
microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-4929dd6-20180301213238
microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-4929dd6-20180301213238
microsoft/dotnet-buildtools-prereqs:ubuntu-16.04
microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-debpkg-d770b8b-20180301213238
microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-coredeps-d770b8b-20180301213238
microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-coredeps
microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-crossdeps-d770b8b-20180301213238
microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-crossdeps
microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-cross-4929dd6-20180301213238
microsoft/dotnet-buildtools-prereqs:ubuntu-17.10-d770b8b-20180301213238
microsoft/dotnet-buildtools-prereqs:ubuntu-17.10
microsoft/dotnet-buildtools-prereqs:ubuntu-17.10-debpkg-d770b8b-20180301213238

**Pull request merged**
