### PR TITLE
Changes for on-prem Helix docker images 

### PR DESCRIPTION
**Pull request by MattGal**
- Change UID of HelixBot to 1001 (to match what's happening)
- Explicitly pre-install virtualenv stuff
- make all use python 3

### CODE REVIEW

**Comment by MattGal** [comment]
@ulisesh please review

**Comment by MattGal** [comment]
I think the most recent changes should get this (one last Helix Ubuntu 18 ARM64 one.

**Comment by MattGal** [comment]
All remaining failures are unrelated to the changes, per Matt this is tracked by https://github.com/dotnet/core-setup/issues/6877 and https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/154, so I'm merging.

**Comment by mthalman** [comment]
Here are the images produced by these changes:

mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.8-helix-arm64v8-a45aeeb-20190620184035
mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-arm32v7-a45aeeb-20190620155842
mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-arm64v8-a45aeeb-20190620155840
mcr.microsoft.com/dotnet-buildtools/prereqs:debian-9-helix-arm32v7-74c9941-20190620155841
mcr.microsoft.com/dotnet-buildtools/prereqs:debian-9-helix-arm64v8-74c9941-20190620155840
mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-helix-arm32v7-a45aeeb-20190620160312
mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-helix-arm64v8-a45aeeb-20190620160300
mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-09a60ed-20190620155854
mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855

**Pull request merged**
