### PR TITLE
Added dockerfiles for ml.net on helix.

### PR DESCRIPTION
**Pull request by michaelgsharp**

### CODE REVIEW

**Comment by michaelgsharp** [comment]
@MattGal here is the docker image PR.

**Review by mthalman — APPROVED** [review]

**Review by MattGal — APPROVED** [review]

**Comment by michaelgsharp** [comment]
Failed due to network timeout
```
Error response from daemon: Get https://mcr.microsoft.com/v2/: dial tcp 255.255.255.255:443: connect: network is unreachable
Error: Retry 5/5 exited 1, no more retries left.
```
I'll rerun the tests.

**Comment by mthalman** [comment]
I restarted the build.

**Pull request merged**
