### PR TITLE
Add ARM legs to PR validation

### PR DESCRIPTION
**Pull request by MichaelSimons**

### CODE REVIEW

**Comment by wfurt** [comment]
are we sure we have enough capacity on ARM systems?

**Comment by MichaelSimons** [comment]
There are currently three ARM leg failures but those are existing issues orthogonal to these changes.

**Comment by MichaelSimons** [comment]
@wfurt - the reason for the failures on the earlier run is related to a config issue with the build agents that has been addressed by DDFUN.

**Pull request merged**
