### PR TITLE
Delete Ubuntu 16.04 and move images to 22.04

### PR DESCRIPTION
**Pull request by am11**

### CODE REVIEW

**Review by mthalman — COMMENTED** [review]
There's not an equal number of file adds compared to deletions. Why are some of the Dockerfiles not being moved over?

**Comment by am11** [comment]
> Why are some of the Dockerfiles not being moved over?

They are not used anymore:

* we previously moved dpkg to Ubuntu 18 and 22 (and used 18 one in runtime)
* 16-cross-arm (32) is not used anywhere in github.com/dotnet org (those legs are moved to newer image).

Moreover, existing tags will continue to work, there are no changes coming to 16.04 anymore from Debian's side, so we won't miss anything. We can gradually move the CI legs to newer LTS images.

**Review by mthalman — APPROVED** [review]
LGTM. Just want to get confirmation from @MattGal too that this will be ok.

**Comment by MattGal** [comment]
> LGTM. Just want to get confirmation from @MattGal too that this will be ok.

No objections here; we maintain "real" ubuntu 16.04 agents anyways for Helix test purposes, so long term .NET Core support for 16.04 shouldn't be affected.  Tagging @rbhanda as an FYI just in case he has concerns too.

**Review by MattGal — APPROVED** [review]

**Pull request merged**
