### PR TITLE
Add crossdac container

### PR DESCRIPTION
**Pull request by sdmaclea**
Add container for testing the cross OS DAC for .NET Core 3.1

### CODE REVIEW

**Comment by jashook** [comment]
lgtm @MichaelSimons ptal

**Comment by hoyosjs** [comment]
Same here. Lgtm

**Comment by sdmaclea** [comment]
@mthalman @MichaelSimons I don't see the `ubuntu-20.04-crossdac-$(System:TimeStamp)-$(System:DockerfileGitCommitSha)` tag in the latest or full tags.  Am I missing something?

**Comment by mthalman** [comment]
@sdmaclea - The build never triggered for some reason.  I've manually queued a build.

**Comment by mthalman** [comment]
Build is done.  Tag results: https://github.com/dotnet/versions/commit/a1642f86922565d91e6c0f2a218eab472ea29443

**Comment by sdmaclea** [comment]
Thanks

**Pull request merged**
