### PR TITLE
Add linux-riscv64 image

### PR DESCRIPTION
**Pull request by am11**

### CODE REVIEW

**Review by mthalman — APPROVED** [review]

**Comment by mthalman** [comment]
Ready to merge or still want a review from @akoeplinger?

**Review by akoeplinger — APPROVED** [review]

**Comment by directhex** [comment]
@mthalman I can't reproduce the build failure locally. `Exec format error` from `chroot` implies there's no `qemu-static` binary for the architecture inside the chroot, but the version of QEMU in `ubuntu-20.04-crossdeps` should be `1:4.2-3ubuntu6.23`, and the `riscv64` binary was added in `1:4.2-3ubuntu6`

**Comment by am11** [comment]
> https://dev.azure.com/dnceng/internal/_build/results?buildId=1915545&view=logs&j=1bc45e3f-6287-5a42-b140-ca49e7cdf8b7&t=eaaa761e-30a0-5df4-5d27-935bf8944a6d

I don't have access to view these logs, but we haven't changed anything in rootfs script since the PR run. Is there any other warning related to binfmt etc. before debootstrap was called? It could be that host machine in official legs are older machines.

> I can't reproduce the build failure locally.

Neither can I. :(

**Comment by mthalman** [comment]
The machines are configured differently between PR and official. There's no mention of binfmt.

The script which installs the pre-reqs on the build machine is defined here: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/ubuntu/build-scripts/install-cross-build-prereqs.sh. Anything that needs to change there? You can see it has `qemu-user-static`.

**Comment by am11** [comment]
Have you find difference in versions of qemu-user-static in official and PR build logs?

From PR logs, the first command looks like:
```
Cloning into '/scripts'...
Running build-rootfs.sh
I: Running command: debootstrap --arch riscv64 --foreign sid /rootfs/riscv64 http://deb.debian.org/debian-ports
```

Is this command different in official build? Is `--foreign` present?

**Comment by am11** [comment]
> Have you find difference in versions of qemu-user-static in official and PR build logs?

In `Install Cross Build Pre-Reqs` step in PR run, I can see:

```
binfmt-support is already the newest version (2.2.0-2).
binfmt-support set to manually installed.
The following NEW packages will be installed:
  qemu qemu-user-static
0 upgraded, 2 newly installed, 0 to remove and 14 not upgraded.
Need to get 21.3 MB of archives.
After this operation, 208 MB of additional disk space will be used.
Get:1 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 qemu amd64 1:4.2-3ubuntu6.23 [15.1 kB]
Get:2 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 qemu-user-static amd64 1:4.2-3ubuntu6.23 [21.2 MB]
Fetched 21.3 MB in 1s (14.3 MB/s)
Selecting previously unselected package qemu.
```

is it different in official build?

**Comment by mthalman** [comment]
**Official (Ubuntu 18.04)**
binfmt-support: 2.1.8-2
qemu-user-static: 1:2.11+dfsg-1ubuntu7.40

**PR (Ubuntu 20.04)**
binfmt-support: 2.2.0-2
qemu-user-static: 1:4.2-3ubuntu6.23

**Comment by am11** [comment]
Can we require Ubuntu 20.04 host for docker files under `src/ubuntu/20.04`?

**Comment by mthalman** [comment]
> Can we require Ubuntu 20.04 host for docker files under `src/ubuntu/20.04`?

.NET Engineering Services doesn't provide agent VM images for 20.04, so no, unfortunately.

**Comment by mthalman** [comment]
@ilyas1974 - Is there any roadmap of having Ubuntu 20.04 available for a VM image in the NetCore1ESPool-Internal pool?

**Comment by am11** [comment]
Ah it's unfortunate. I will try to find a workaround for 18.04. Btw, Ubuntu 18.04 will be out of support in ~10 months.

**Comment by am11** [comment]
Hopefully this workaround will do the trick in the meantime: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/647. Could you please trigger the official leg to find out if it helps?

**Comment by directhex** [comment]
> Ah it's unfortunate. I will try to find a workaround for 18.04. Btw, Ubuntu 18.04 will be out of support in ~10 months.

Well *sucks teeth* not that I'd recommend it per se, but `qemu-user-static`, as the name implies, statically links everything. Such that the package from 20.04 installs fine on 18.04, unmodifed. 

```
root@beth:/tmp# dpkg -i qemu-user-static_4.2-3ubuntu6.23_amd64.deb 
(Reading database ... 9553 files and directories currently installed.)
Preparing to unpack qemu-user-static_4.2-3ubuntu6.23_amd64.deb ...
Unpacking qemu-user-static (1:4.2-3ubuntu6.23) over (1:2.11+dfsg-1ubuntu7.40) ...
Setting up qemu-user-static (1:4.2-3ubuntu6.23) ...
root@beth:/tmp#
```

And, indeed, the package from 22.04 also works.

```
root@beth:/tmp# dpkg -i qemu-user-static_6.2+dfsg-2ubuntu6.3_amd64.deb 
(Reading database ... 9592 files and directories currently installed.)
Preparing to unpack qemu-user-static_6.2+dfsg-2ubuntu6.3_amd64.deb ...
Unpacking qemu-user-static (1:6.2+dfsg-2ubuntu6.3) over (1:4.2-3ubuntu6.23) ...
Setting up qemu-user-static (1:6.2+dfsg-2ubuntu6.3) ...
root@beth:/tmp#
```

So if we forcibly download the post-18.04 .deb and install it...

**Comment by am11** [comment]
I think we need to update binfmt as well. Lets see if switching repositories (#647) helps.

**Comment by directhex** [comment]
Focal binfmt package works, Jammy package needs a too-new glibc which will break the world

**Pull request merged**
