### PR TITLE
Add helix platform support for Alpine 3.13

### PR DESCRIPTION
**Pull request by am11**
Also, reorganize 3.14, so we have some uniformity across versions (3.12 onwards):

`src/alpine/{version}/WithNode`
`src/alpine/{version}/helix/{arch}`

Plan is to drop 3.12 and below for .NET 6, per https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md#linux and https://github.com/dotnet/runtime/pull/57324#issuecomment-911761191

cc @ViktorHofer

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@mthalman requested a review from you as I don't know what the usual process for this repo is, hope that's fine.

**Comment by am11** [comment]
> `src/alpine/{version}/WithNode`
> `src/alpine/{version}/helix/{arch}`

@mthalman, at least for dotnet/runtime, we don't need `src/alpine/{version}/{arch}` variants at the moment, so I have renamed them to helix. Please let me know if it is ok.

**Comment by mthalman** [comment]
You mention the WithNode variants but your changes haven't done anything with those Dockerfiles.  The WithNode variants are dependent on the `mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-{version}` local tag which you had removed as part of deleting the `src/alpine/{version}/{arch}/Dockerfile` files.  This is what is causing the build to fail.

**Comment by am11** [comment]
Yes I noticed `IsLocal: true` was required.
My question was actually if just having `WithNode` and `helix` for all `src/alpine/{version}`s a good approach, or would you rather have `src/alpine/{version}/{arch}` in addition to `src/alpine/{version}/helix/{arch}`?

**Comment by mthalman** [comment]
> My question was actually if just having `WithNode` and `helix` for all `src/alpine/{version}`s a good approach, or would you rather have `src/alpine/{version}/{arch}` in addition to `src/alpine/{version}/helix/{arch}`?

I have no opinion on that as I'm not involved, nor familiar, with the actual usage of the image tags.

**Comment by mthalman** [comment]
I believe the build is failing because the WithNode Dockerfiles are now based on helix which sets the user to helixbot. So the build for WithNode doesn't have permissions to run apk. I think setting the user to ContainerAdministrator to run the necessary commands and then switching back to helixbot would solve this.

**Review by mthalman — APPROVED** [review]

**Comment by am11** [comment]
Used a slightly different approach (to avoid switching users); extracted out common amd64 steps in `{version}/arm64/Dockerfile`, which are shared between `helix/amd64` and `WithNode/amd64`.

**Review by mthalman — APPROVED** [review]

**Comment by ViktorHofer** [comment]
@am11 I assume the PR is ready to be merged?

**Comment by am11** [comment]
Yup, all essentials are in :shipit:
For the rest of nifty deduplication ideas, I have posted my mind dump in related thread https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/231#issuecomment-912585330, but it's out of scope of this PR. 😅

**Comment by mthalman** [comment]
Build is failing due to an infrastructure issue. I'm investigating.

**Comment by mthalman** [comment]
I've got a fix for it here: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/498

**Pull request merged**
