### PR TITLE
Update MsQuic on Ubuntu 18.04

### PR DESCRIPTION
**Pull request by CarnaViire**
cc @wfurt @ManickaP @mthalman

### CODE REVIEW

**Review by ManickaP — APPROVED** [review]

**Review by mthalman — APPROVED** [review]

**Comment by mthalman** [comment]
@lbussell - It appears the Ubuntu builds are broken unrelated to these changes.

**Comment by CarnaViire** [comment]
I assume this is the same problem as https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/903 😢

**Comment by lbussell** [comment]
Taking a look at the failure.

**Comment by wfurt** [comment]
I think this needs never node @lbussell. 
```
#7 [4/7] RUN npm install -g npm
#7 0.775 npm ERR! code EBADENGINE
#7 0.777 npm ERR! engine Unsupported engine
#7 0.777 npm ERR! engine Not compatible with your version of node/npm: npm@10.2.0
#7 0.777 npm ERR! notsup Not compatible with your version of node/npm: npm@10.2.0
#7 0.777 npm ERR! notsup Required: {"node":"^18.17.0 || >=20.5.0"}
#7 0.777 npm ERR! notsup Actual:   {"npm":"8.19.2","node":"v18.12.1"}
#7 0.779 
```

**Comment by lbussell** [comment]
> @wfurt: I think this needs newer node

Yeah, that was it, got it building locally so let's hope that's the only issue.

**Comment by lbussell** [comment]
> The Raspbian may be different issue. I was trying to figure out of I can build arm32 on arm64.... and in mean time I'm refreshing my Raspberry so I can possibly build arm32 natively.

I didn't see a Raspbian issue, don't see it in the [public pipeline runs](https://dev.azure.com/dnceng-public/public/_build?definitionId=57) either. You should be able to build arm32 on arm64 by using the `--platform linux/arm32/v7` argument on the build command.

**Comment by lbussell** [comment]
OK, trying to fix that issue by adding `rustc`. From my research, the `CRYPTOGRAPHY_DONT_BUILD_RUST` env variable might have been a temporary workaround. If we run into compilation issues (which is likely), we should try updating the pip version, which is the official recommendation from [cryptography](https://github.com/pyca/cryptography). I'm trying this first because I don't know if helix relies on a specific pip version.

**Comment by wfurt** [comment]
I have access to arm64 build machine so I can try more if needed @lbussell. 
Some images use `pip==22.0.4` and `virtualenv==20.14.0` so I would expect that should be good enough. 
If needed I would suggest to lock it on that version to decrease variations.

**Comment by wfurt** [comment]
actually, Ubuntu 18.04 is EOL https://ubuntu.com/blog/ubuntu-18-04-eol-for-devices
Instead of trying to wrestle unsupported OS we should perhaps move to 20.04 or 22.04.

**Comment by lbussell** [comment]
It'd be great to drop 18.04 - but don't we still need to keep this image buildable to support .NET 6 and 7?

**Comment by lbussell** [comment]
Actually, this 18.04 image isn't even being updated in this PR, the image exists in MCR already, it won't get any more security updates, so we should just delete it. If Raspbian 10 is blocking any other PRs we should consider a similar approach there.

**Comment by lbussell** [comment]
@wfurt, @CarnaViire, @ManickaP, would moving the failing runtime tests to 20.04/22.04 unblock your PR?

**Comment by lbussell** [comment]
So @wfurt, @CarnaViire, @ManickaP, this is building now, but I would still probably recommend moving the 8.0/main tests off 18.04 especially if we aren't supporting it for 8.0/9.0. These Dockerfiles should all be removed soon.

**Comment by CarnaViire** [comment]
@lbussell Debian 10 and Debian 11 Arm images are [also failing](https://dev.azure.com/dnceng/internal/_build/results?buildId=2295639&view=results) -- I assume the same changes should be applied to them? I'll try to put up a PR with that

**Pull request merged**
