### PR TITLE
Update to build a 16.04 rootfs

### PR DESCRIPTION
**Pull request by jashook**
14.04 is eol, we should not be building the rootfs using it, even if it is just for the crossbuild.

### CODE REVIEW

**Comment by jashook** [comment]
@jkoritzinsky @trylek ptal

**Comment by jkoritzinsky** [comment]
cc: @janvorli

**Comment by MichaelSimons** [comment]
I agree 14.04 should be removed.  That being said how is the new proposed image different than the one produced [here](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/manifest.json#L303)?

**Comment by jashook** [comment]
I will confirm; however, I believe that one does not include the rootfs for x86 and armhf

**Comment by jashook** [comment]
Nope, they are the same. I will remove the 16.04 folder.

**Comment by jashook** [comment]
Ok this should be ready for review now, addressing @MichaelSimons comment

**Pull request merged**
