### PR TITLE
switch to msquic main to pick up arm fixes

### PR DESCRIPTION
**Pull request by wfurt**
fixes preventing test runs are in main now. (and will flow to msquic 2.1.1 eventually)

### CODE REVIEW

**Review by rzikm — APPROVED** [review]

**Comment by mthalman** [comment]
Builds are failing:

```
cp: cannot stat 'artifacts/bin/linux/arm64_Release_openssl/libmsquic.lttng.so.2.1.0': No such file or directory
```

**Review by rzikm — CHANGES_REQUESTED** [review]
Main is building different version, apparently
> arm64_Release_openssl/libmsquic.so.2.2.0

**Comment by wfurt** [comment]
It seems like the build just retires in loop and then it fails with timeout @mthalman. It would be nice if it just fails with the error at the end...

**Comment by mthalman** [comment]
> It seems like the build just retires in loop and then it fails with timeout @mthalman. It would be nice if it just fails with the error at the end...

Yeah, it's unfortunate. The retry is useful because often times there are connectivity issues with stuff being accessed as part of the build. The retry means you don't have to start from scratch with these really long builds, assuming that a retry fixes the issue. The only way to fix it is to ensure the timeout is long enough to account for retries. But that has a downside as well if something gets blocked in the build, it can cause a waste of resources if the timeout is really long. It's all about striking a balance.

**Comment by wfurt** [comment]
I see it useful for intermittent failures. Maybe limit it to just 1 or 2? But I also learned my lesson. I'm always suspicious of ARM because of timing and performance so I did not dig deeper into the logs.

**Review by rzikm — APPROVED** [review]

**Pull request merged**
