### PR TITLE
Fix Fedora rawhide build issue

### LINKED ISSUE #401: Fedora rawhide build fails installing packages
Build is failing for this Dockerfile: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/src/fedora/rawhide/amd64/Dockerfile

Docker build output:

```
Step 1/5 : FROM fedora:rawhide
 ---> 10b640fb5093
Step 2/5 : RUN rpm --import https://src.fedoraproject.org/rpms/fedora-repos/raw/master/f/RPM-GPG-KEY-fedora-34-primary
 ---> Using cache
 ---> b68288a995eb
Step 3/5 : RUN dnf install -y         clang         cmake         findutils         gdb         glibc-langpack-en         lldb-devel         llvm-devel         make         python         which     && dnf clean all
 ---> Running in f4eefd820da6
Fedora 34 openh264 (From Cisco) - x86_64        2.7 kB/s | 2.5 kB     00:00    
Fedora - Modular Rawhide - Developmental packag 3.3 MB/s | 5.5 MB     00:01    
Fedora - Rawhide - Developmental packages for t  15 MB/s |  73 MB     00:04    
Error: 
 Problem: conflicting requests
  - package lldb-devel-11.1.0-1.rc1.fc34.i686 requires liblldb.so.11, but none of the providers can be installed
  - package lldb-devel-11.1.0-1.rc1.fc34.i686 requires liblldbIntelFeatures.so.11, but none of the providers can be installed
  - package lldb-devel-11.1.0-1.rc1.fc34.i686 requires lldb(x86-32) = 11.1.0-1.rc1.fc34, but none of the providers can be installed
  - package lldb-devel-11.1.0-1.rc1.fc34.x86_64 requires liblldb.so.11()(64bit), but none of the providers can be installed
  - package lldb-devel-11.1.0-1.rc1.fc34.x86_64 requires liblldbIntelFeatures.so.11()(64bit), but none of the providers can be installed
  - package lldb-devel-11.1.0-1.rc1.fc34.x86_64 requires lldb(x86-64) = 11.1.0-1.rc1.fc34, but none of the providers can be installed
  - nothing provides libclang-cpp.so.11 needed by lldb-11.1.0-1.rc1.fc34.i686
  - nothing provides libclang-cpp.so.11()(64bit) needed by lldb-11.1.0-1.rc1.fc34.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

### PR DESCRIPTION
**Pull request by mthalman**
Fixes #401

### CODE REVIEW

**Review by MichaelSimons — APPROVED** [review]
These changes look fine.  Should the other Fedora based Dockerfiles be pulling images from the fedora registry as well?

**Comment by omajid** [comment]
> Should the other Fedora based Dockerfiles be pulling images from the fedora registry as well?

That's a good question. My understanding is that the Fedora registry just gets updated more quickly (dockerhub has a lag). Otherwise the images are the same. The timing (faster updates) might matter for security fixes if we build on top of the fedora base image and dont do a `dnf update` to pick up the latest fixes.

**Comment by mthalman** [comment]
I've updated things to use the Fedora registry consistently.

I've also removed Dockerfiles for EOL versions of Fedora.  FYI @MattGal

**Review by MichaelSimons — APPROVED** [review]

**Comment by MattGal** [comment]
> I've updated things to use the Fedora registry consistently.
> 
> I've also removed Dockerfiles for EOL versions of Fedora. FYI @MattGal

Seems fine to me, is there a reason it's rawhide and not a number?

**Comment by mthalman** [comment]
> Seems fine to me, is there a reason it's rawhide and not a number?

[Rawhide](https://fedoraproject.org/wiki/Releases/Rawhide) is the codename for the current in-development version.

**Comment by MattGal** [comment]
> > Seems fine to me, is there a reason it's rawhide and not a number?
> 
> [Rawhide](https://fedoraproject.org/wiki/Releases/Rawhide) is the codename for the current in-development version.

Understood just seemed like it'd end up as 34 after that.

**Comment by mthalman** [comment]
> Understood just seemed like it'd end up as 34 after that.

Sure, but it's pointing to the rawhide tag which would change over time.  So I'd be hesitant to tag it as 34.  I'm not sure where this image is being used.  Presumably, if 34 was needed at the point that a `34` tag was available, we'd need to add a separate Dockerfile for it at that time.

**Comment by omajid** [comment]
> Understood just seemed like it'd end up as 34 after that.

Actually, what's `rawhide` right now is what will become Fedora 35. `rawhide` was actually pointing to 34 a few weeks ago, so it's very much a in-flux tag.

**Pull request merged**
