### PR TITLE
Use Mariner not Ubuntu as armv6 host image

### PR DESCRIPTION
**Pull request by directhex**
This is expected to fail until https://github.com/dotnet/arcade/pull/14730 is merged (it doesn't need to flow to any branches once merged since rootfs generation always uses arcade git main)

### CODE REVIEW

**Review by mthalman — APPROVED** [review]

**Review by mthalman — APPROVED** [review]
@directhex - Are these changes good to merge?

**Comment by directhex** [comment]
I don't see why not. Then we can change the image used in runtime and everything will be just peachy

**Comment by mthalman** [comment]
GitHub is having issues. This is showing and not updating:

image

I'm going to try closing and re-opening.

**Comment by mthalman** [comment]
Ah, now it's fixed. Just needed a comment.

**Pull request merged**
