### PR TITLE
Add brotli to sourcebuild container

### PR DESCRIPTION
**Pull request by agocke**
Part of https://github.com/dotnet/runtime/pull/107225

### CODE REVIEW

**Review by mthalman — COMMENTED** [review]
This new dependency will need to be applied equally to all the container images used for source build. Please ensure that all of these contain brotli if they don't already: https://github.com/dotnet/sdk/blob/7dc1e29627f20d47213ef2623b9e74b0e3cb4a4f/eng/pipelines/templates/variables/vmr-build.yml#L15-L28

**Comment by agocke** [comment]
Thanks for the list, thought it was strange we only had one source build image.

**Comment by agocke** [comment]
One thing is: I only need to update non-portable builds. Which ones are those?

**Comment by mthalman** [comment]
> One thing is: I only need to update non-portable builds. Which ones are those?

All of the builds for source build are non-portable.

**Comment by agocke** [comment]
Does source build support cross build? Or does it just share the container?

**Comment by mthalman** [comment]
> Does source build support cross build? Or does it just share the container?

We don't run cross build in these containers for source build. Unified build has its own set of containers for cross build: https://github.com/dotnet/sdk/blob/7dc1e29627f20d47213ef2623b9e74b0e3cb4a4f/eng/pipelines/templates/variables/vmr-build.yml#L29-L48

**Review by mthalman — COMMENTED** [review]
What about Fedora: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/fedora/40/amd64/Dockerfile. I see it already implicitly has `libbrotli` installed, but not `brotli-devel`.

**Comment by agocke** [comment]
@mthalman Thanks, fixed.

**Review by mthalman — APPROVED** [review]

**Pull request merged**
