### PR TITLE
Add python-pip3 to the list of Ubuntu apt package dependencies

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Comment by BruceForstall** [comment]
This is needed for https://github.com/dotnet/runtime/pull/74961, where it appears that only 18.04 is needed, but it makes sense to add it to all the versions to support possible future version roll forward.

**Comment by BruceForstall** [comment]
@MattGal

**Review by MattGal — APPROVED** [review]

**Comment by BruceForstall** [comment]
@mthalman Thanks for triggering the run; I wasn't aware of this.

Unfortunately, there seem to be a lot of presumably unrelated failures, so how do I interpret the results?

**Comment by mthalman** [comment]
@BruceForstall - That's normally not needed. It was needed because things weren't working from the dnceng-public migration. Getting close to having things in a working state.

**Review by mthalman — APPROVED** [review]

**Comment by BruceForstall** [comment]
@mthalman Thanks!

@mthalman @MattGal How does this change propagate such that we use the new Docker containers as the containers for the Linux/arm and Linux/arm64 AzDO builds in the dotnet/runtime internal repo pipelines?

**Comment by wfurt** [comment]
You will need to update references under eng/pipeline/coreclr/.... @BruceForstall

**Comment by wfurt** [comment]
yes, https://github.com/dotnet/runtime/pull/75167 looks right to me.

**Comment by BruceForstall** [comment]
Ok, it looks like there's some step missing.

In this PR, the build of "Linux_amd64 src-ubuntu-18.04-coredeps-graph", step "Build Images", includes:
```
IMAGES BUILT
------------
...
mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-cross-arm-20220906173739-70ed2e8
...
mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-cross-arm64-20220906173739-70ed2e8
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=5861&view=logs&jobId=9aada89a-2e24-5acb-2807-6900158b9cce&j=fc59f0f2-c1bd-58ae-b870-833d1e8a924c&t=8d53baa0-ff68-5ea5-041a-af0e08303d7f

But my PR to use these new images:

https://github.com/dotnet/runtime/pull/75167

is failing with:

```
/usr/bin/docker pull mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-cross-arm-20220906173739-70ed2e8
Error response from daemon: manifest for mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-cross-arm-20220906173739-70ed2e8 not found: manifest unknown: manifest tagged by "ubuntu-18.04-cross-arm-20220906173739-70ed2e8" is not found
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=6487&view=logs&jobId=a83666f7-a1cf-595f-f6cb-b187860111f1&j=a83666f7-a1cf-595f-f6cb-b187860111f1&t=5c3ca8e6-53e6-49f0-b8ff-a6c07d00604f

What am I missing? @wfurt @mthalman @MattGal

**Comment by wfurt** [comment]
The latest (link from top page) https://github.com/dotnet/versions/blob/main/build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-main.json
shows `ubuntu-18.04-cross-arm-20220906173811-70ed2e8` and `ubuntu-18.04-cross-arm64-20220906173811-70ed2e8`

**Comment by wfurt** [comment]
```
furt@ubu18:~$ docker run --rm -ti mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-cross-arm-20220906173811-70ed2e8 bash
Unable to find image 'mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-cross-arm-20220906173811-70ed2e8' locally
ubuntu-18.04-cross-arm-20220906173811-70ed2e8: Pulling from dotnet-buildtools/prereqs
22c5ef60a68e: Already exists
c678bd3d1071: Pull complete
3a1ca280cb77: Pull complete
7bde3cf127f0: Pull complete
b4cb006e7f92: Pull complete
73c23866a4ae: Pull complete
8e5f03469102: Pull complete
Digest: sha256:309b48001fc2962772d804ab64acbd4b0a4283f5887cef1a97b44361b79c782c
Status: Downloaded newer image for mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-cross-arm-20220906173811-70ed2e8
```

I'm not sure where you look. But when PR is merged it would kick another build on "official" internal machine pool and it would publish images from there.

**Comment by BruceForstall** [comment]
> I'm not sure where you look. But when PR is merged it would kick another build on "official" internal machine pool and it would publish images from there.

ok, makes sense.

I see an internal build pipeline dotnet-buildtools-prereqs-docker-ubuntu that picked up my change, but it looks like it was manually cancelled by @mthalman ?

https://dev.azure.com/dnceng/internal/_build?definitionId=443&_a=summary

**Comment by mthalman** [comment]
I canceled the build because another merged PR already had a build running. We try to avoid have simultaneous builds for the same pipeline because that can result in unnecessary waste of resources by not taking advantage of our image caching functionality. I have a new build running with these changes: https://dev.azure.com/dnceng/internal/_build/results?buildId=1986251&view=results.

**Comment by BruceForstall** [comment]
The new build finished, https://github.com/dotnet/versions/blob/main/build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-main.json is updated, I verified the published containers have pip3 (that I added), so I updated https://github.com/dotnet/runtime/pull/75167

**Pull request merged**
