### PR TITLE
Update Alpine images

### PR DESCRIPTION
**Pull request by MattGal**
Helix needs Python 3 as default, deprecate 3.6 as it's been EOL since May.

@wtgodbe FYI.

### CODE REVIEW

**Comment by mthalman** [comment]
Looks like there's a problem running pip in the Debian 9 Dockerfiles.

**Comment by MattGal** [comment]
> Looks like there's a problem running pip in the Debian 9 Dockerfiles.

Should be fixed now, just was only installing pip for python v2.

**Comment by MattGal** [comment]
All relevant builds green, merging (remaining is ubuntu, didn't touch it)

**Comment by wtgodbe** [comment]
@mthalman is there a way to track the progress of publishing the new images?

**Comment by mthalman** [comment]
@wtgodbe - The internal link for the builds is here: https://dev.azure.com/dnceng/internal/_build?path=%5Cdotnet%5Cdotnet-buildtools-prereqs-docker.  There are separate pipelines for each of the root folders.  I'll post back here with the list of tags when the images are ready.

**Comment by mthalman** [comment]
The following images were published:

mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-7c6abd3-20190611191932
mcr.microsoft.com/dotnet-buildtools/prereqs:debian-jessie-coredeps-3e800f1-20190611191928
mcr.microsoft.com/dotnet-buildtools/prereqs:debian-jessie-3e800f1-20190611191928
mcr.microsoft.com/dotnet-buildtools/prereqs:debian-jessie-debpkg-58e4974-20190611191928
mcr.microsoft.com/dotnet-buildtools/prereqs:debian-jessie-corert-58e4974-20190611191928
mcr.microsoft.com/dotnet-buildtools/prereqs:debian-stretch-3e800f1-20190611191935
mcr.microsoft.com/dotnet-buildtools/prereqs:debian-stretch-docker-testrunner-63f2145-20190611191931
mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-arm64v8-7c6abd3-20190611191844
mcr.microsoft.com/dotnet-buildtools/prereqs:debian-9-arm64v8-3e800f1-20190611191844
mcr.microsoft.com/dotnet-buildtools/prereqs:debian-9-helix-arm64v8-96958d6-20190611191845
mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-arm32v7-7c6abd3-20190611191844
mcr.microsoft.com/dotnet-buildtools/prereqs:debian-9-arm32v7-0dbbad8-20190611191844
mcr.microsoft.com/dotnet-buildtools/prereqs:debian-9-helix-arm32v7-96958d6-20190611191845
mcr.microsoft.com/dotnet-buildtools/prereqs:debian-iot-arm32v7-be5b37d-20190611191846

mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.8-helix-09ca40b-20190611191928
mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.9-0fc54a3-20190611191928
mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.9-WithNode-0fc54a3-20190611191928
mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.9-helix-09ca40b-20190611191939
mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.8-helix-arm64v8-09ca40b-20190611191839
mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.9-arm64v8-0fc54a3-20190611191839

**Comment by wtgodbe** [comment]
I've updated https://github.com/dotnet/corefx/pull/38404 accordingly

**Pull request merged**
