### PR TITLE
Add missing Fedora27 dependency

### PR DESCRIPTION
**Pull request by ianhays**
I missed one somehow. I verified twice that I've got them all now.

PTAL @MichaelSimons

### CODE REVIEW

**Comment by MichaelSimons** [comment]
@dotnet-bot test fedora please
@dotnet-bot test ubuntu_14 please

**Comment by ianhays** [comment]
Fedora23 build appears to be failing for some reason.

**Comment by ianhays** [comment]
Thanks Michael.

**Comment by MichaelSimons** [comment]
The following image was produced as a result of this PR"
microsoft/dotnet-buildtools-prereqs:fedora-27-679b52b-20180403194933

**Pull request merged**
