### PR TITLE
Add docker image w/ both Android SDK and an x64 crossroot

### PR DESCRIPTION
**Pull request by directhex**
(for AllSubsets jobs)

### CODE REVIEW

**Comment by directhex** [comment]
Sigh. How do I get the intra-dependency to show up?

**Review by jkoritzinsky — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
You need to depend on the -local versions of the base images and add local tags for the base images in the manifest if they aren't there already.

**Comment by directhex** [comment]
`write /var/lib/docker/tmp/GetImageBlob1305137427: no space left on device` I think it's time to hit the tequila

**Comment by directhex** [comment]
This seems OK now? (thanks @lbussell)

Can I get a re-review @jkoritzinsky?

**Review by jkoritzinsky — APPROVED** [review]

**Pull request merged**
