### PR TITLE
[Rollout] Production rollout - 2023-01-18

### PR DESCRIPTION
**Pull request by AlitzelMendez**
latest main build: https://dnceng.visualstudio.com/internal/_build/results?buildId=2090467&view=results

### CODE REVIEW

**Comment by mthalman** [comment]
The changes from one of the merged commits, https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/754, is causing a break for some reason: https://dev.azure.com/dnceng/internal/_build/results?buildId=2090449&view=logs&j=89424110-4656-5e6e-83be-f8cf1ddf2101&t=b3007bc9-5265-5f57-b69a-8ad546c51437.  I'm investigating.

**Review by riarenas — DISMISSED** [review]

**Comment by michellemcdaniel** [comment]
I'm wondering if this is a crlf issue

**Comment by mthalman** [comment]
It's an infrastructure bug. I have a fix at https://github.com/dotnet/docker-tools/pull/1109. After this gets merged, it'll get rolled out to this repo. I'll respond here with the commit to add to this PR when it's available.

**Comment by mthalman** [comment]
Ok, I have a commit from https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/771 that will unblock the build: 00327c9. That commit should get included here. But it will likely fail in the publish stage of the pipeline. That's ok because I can manually tweak the run after the fact to get the images published. So once again we'll need to baby sit this through. The failure in publish I think is due to a concurrency bug in .NET 7 now that we've upgraded our infrastructure to .NET 7. I'll be investigating that today.

**Comment by AlitzelMendez** [comment]
@mthalman I added the commit that you mention. let me know if this is ready to rollout and if that is the case, please approve the PR, thanks!

**Review by michellemcdaniel — APPROVED** [review]

**Review by premun — APPROVED** [review]

**Pull request merged**
