### PR TITLE
Update centos7 rpmpkg to use ruby 2.5

### PR DESCRIPTION
**Pull request by wtgodbe**
Attempt to update the centos7 image to fix https://github.com/dotnet/aspnetcore/issues/37406.

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
I don't know whether they're better nor whether all remain compatible w/ CentOS 7 but `rh-ruby26*`, `rh-ruby27*`, and `rh-ruby30` packages are available.

**Comment by wtgodbe** [comment]
@mthalman I separated it out to try to find which install command was failing:

> Step 7/9 : RUN gem install --no-document         git:1.7.0         ffi:1.12.2
 ---> Running in 22bbc5163ece
/bin/sh: gem: command not found

does `RUN yum --enablerepo=centos-sclo-rh -y install rh-ruby25-rubygems` not achieve that?

**Comment by mthalman** [comment]
> @mthalman I separated it out to try to find which install command was failing:

If you're still working on debugging the Dockerfile, it would be better to mark this as a draft PR. In addition, it would be better to install Docker Desktop on your local machine and build the Dockerfile locally to diagnose issues.

> > Step 7/9 : RUN gem install --no-document         git:1.7.0         ffi:1.12.2
> > ---> Running in 22bbc5163ece
> > /bin/sh: gem: command not found
> 
> does `RUN yum --enablerepo=centos-sclo-rh -y install rh-ruby25-rubygems` not achieve that?

I don't have much experience in this area. Looking at the other Dockerfiles in this repo that use gem, I see they just install `rubygems`.

**Comment by wtgodbe** [comment]
Ok, should be working now

**Review by dougbu — APPROVED** [review]

**Review by mthalman — APPROVED** [review]

**Pull request merged**
