### PR TITLE
add krb5-libs to Alpine 3.17 image

### PR DESCRIPTION
**Pull request by wfurt**
missed in #799

### CODE REVIEW

**Review by mthalman — APPROVED** [review]

**Comment by mthalman** [comment]
@wfurt - Be aware that now all merges to main have the "production" tagging pattern. No more `-staging` suffixes for images from main. See https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/814

**Comment by wfurt** [comment]
oh. I did not know.  What is the recommended pattern for development and updates?

**Comment by mthalman** [comment]
> oh. I did not know. What is the recommended pattern for development and updates?

There is none anymore. This is a consequence of the Eng. Services team reorg.

**Comment by wfurt** [comment]
ok. understand. We could always go back to using the explicit tags if we need to.

**Pull request merged**
