### PR TITLE
[Rollout] Production deployment, 2023-02-01

### PR DESCRIPTION
**Pull request by riarenas**

### CODE REVIEW

**Comment by mthalman** [comment]
@riarenas - I'd like to get https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/784 included in these changes as well.

**Comment by riarenas** [comment]
Sounds good. I can add it once it's merged.

**Comment by mthalman** [comment]
> Sounds good. I can add it once it's merged.

@riarenas - It's merged now. Commit: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/commit/3f712e89030033aea75c8e924857a0ec1d4deeb1

**Comment by riarenas** [comment]
> > Sounds good. I can add it once it's merged.
> 
> @riarenas Ricardo Arenas FTE - It's merged now. Commit: [3f712e8](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/commit/3f712e89030033aea75c8e924857a0ec1d4deeb1)

Added!

**Review by michellemcdaniel — APPROVED** [review]

**Pull request merged**
