### PR TITLE
WebAssembly: Update emscripten to 2.0.1

### PR DESCRIPTION
**Pull request by akoeplinger**

### CODE REVIEW

**Comment by akoeplinger** [comment]
@mthalman it looks like the internal build failed with this, any ideas:

```
System.InvalidOperationException: Unable to find platform data for tag 'dotnetdocker.azurecr.io/build-staging/788927/dotnet-buildtools/prereqs:ubuntu-18.04-coredeps'. It's likely that the platforms are not ordered according to dependency.
   at Microsoft.DotNet.ImageBuilder.Commands.BuildCommand.SetPlatformDataBaseDigest(PlatformData platform, PlatformInfo manifestPlatform, Dictionary`2 platformDataByTag) in /image-builder/src/Commands/BuildCommand.cs:line 125
   at Microsoft.DotNet.ImageBuilder.Commands.BuildCommand.PublishImageInfo() in /image-builder/src/Commands/BuildCommand.cs:line 91
   at Microsoft.DotNet.ImageBuilder.Commands.BuildCommand.ExecuteAsync() in /image-builder/src/Commands/BuildCommand.cs:line 52
   at Microsoft.DotNet.ImageBuilder.ImageBuilder.Main(String[] args) in /image-builder/src/ImageBuilder.cs:line 66
```

https://dev.azure.com/dnceng/internal/_build/results?buildId=788927&view=results

**Comment by mthalman** [comment]
Looking into it.  I'll respond again once an updated image is published.

**Comment by mthalman** [comment]
Build is complete.  Published tags are available here: https://github.com/dotnet/versions/commit/73929e8cfe366cb347428d22299ce8fa73fc2def

**Comment by akoeplinger** [comment]
Thank you!

**Pull request merged**
