### PR TITLE
Add Mono build dependencies

### PR DESCRIPTION
**Pull request by akoeplinger**

### CODE REVIEW

**Comment by ViktorHofer** [comment]
cc @MichaelSimons

**Comment by mthalman** [comment]
In the Fedora and Ubuntu Dockerfiles, `automake` is listed before `autoconf`.  Please reverse the order of those so they are alphabetical.

**Comment by akoeplinger** [comment]
@mthalman done :)

**Comment by akoeplinger** [comment]
@MichaelSimons can we merge this without waiting for the centos builds? they take about three hours and were green before making the alphabetical order change.

**Comment by MichaelSimons** [comment]
@akoeplinger - I am alright with merging.

**Comment by mthalman** [comment]
Builds are failing during publish phase due to an infrastructure issue. Fixing...

**Comment by mthalman** [comment]
The build issues have been resolved by https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/234.  I've re-run the publishing of all the affected images and they're all good now.

**Pull request merged**
