### PR TITLE
Remove usage of Windows Server, version 1909

### PR DESCRIPTION
**Pull request by mthalman**
Windows Server, version 1909 is EOL as of May 11, 2021.

### CODE REVIEW

**Comment by MichaelSimons** [comment]
@MattGal - FYI

**Review by MattGal — APPROVED** [review]

**Comment by MattGal** [comment]
@safern  also FYI.  If GitHub search works runtime may actually already not be using this one any more.

**Comment by safern** [comment]
We might be using it in corefx release/3.1 but I couldn't find any usage on dotnet/runtime using GH search.

**Comment by MattGal** [comment]
> We might be using it in corefx release/3.1 but I couldn't find any usage on dotnet/runtime using GH search.

Same here but GH search isn't the greatest thing.  The old images keep working regardless, you just are on top of deprecating dead things.

**Pull request merged**
