### PR TITLE
correct UID for helixbot user

### PR DESCRIPTION
**Pull request by wfurt**
When I did cleanup to make user consistent I picked UID from one of existing file. Turned out it was wrong as helixbot on base image is 1000 and not 1001.

### CODE REVIEW

**Comment by wfurt** [comment]
I don't have currently good way how to test this with Helix. It may exist but I'm not aware of it. 
And I don't understand your question about UID.
If the UIS is not same as UID on host machine, tests will fail like they do right now with:
```
BEGIN EXECUTION]
chmod: changing permissions of '/root/helix/work/workitem/RunTests.sh': Operation not permitted
+ ./RunTests.sh --runtime-path /root/helix/work/correlation --dotnet-root /root/helix/work/correlation
```

**Comment by MattGal** [comment]
@wfurt to test this we'd need to push the resultant image to a container registry (dockerhub, mcr, or my private one) and send off some jobs.

**Comment by wfurt** [comment]
yes, I can do that when @MichaelSimons  builds new images.

**Comment by wfurt** [comment]
seems like Ubuntu17 is gone from servers. That looks independent of this PR.

**Comment by MattGal** [comment]
@wfurt yes, the odd-numbered Ubuntus only live 9 months, so all 17.x is gone.

**Pull request merged**
