### PR TITLE
Remove lldb-dev package from alpine.3.6 image

### LINKED ISSUE #55: Alpine 3.6 images no longer build
15:43:56 Step 5/5 : RUN apk -X https://dl-cdn.alpinelinux.org/alpine/edge/testing add --no-cache         lldb-dev
15:43:57  ---> Running in a844d5b9f3e7
15:43:59 fetch https://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
15:44:00 fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
15:44:00 fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
15:44:00 [91mWARNING: This apk-tools is OLD! Some packages might not function properly.
15:44:00 [0m[91mERROR: unsatisfiable constraints:
15:44:00 [0m  so:libLLVM-5.0.so (missing):
15:44:00     required by: lldb-5.0.1-r0[so:libLLVM-5.0.so]
15:44:00                  lldb-5.0.1-r0[so:libLLVM-5.0.so]
15:44:00                  lldb-5.0.1-r0[so:libLLVM-5.0.so]
15:44:00                  lldb-5.0.1-r0[so:libLLVM-5.0.so]
15:44:00                  lldb-5.0.1-r0[so:libLLVM-5.0.so]
15:44:00                  lldb-5.0.1-r0[so:libLLVM-5.0.so]
15:44:00                  lldb-5.0.1-r0[so:libLLVM-5.0.so]
15:44:13 The command '/bin/sh -c apk -X https://dl-cdn.alpinelinux.org/alpine/edge/testing add --no-cache         lldb-dev' returned a non-zero code: 3

### PR DESCRIPTION
**Pull request by MichaelSimons**
Removing the problematic llbd-dev package per https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/55#issuecomment-406028856

Fixes #55 

@mikem8361 - can you take a look?  Is this going to be acceptable?  Is there a different solution you would like to see?  We need to get CI passing which is why I am proposing this change.

### CODE REVIEW

**Comment by MichaelSimons** [comment]
@mikem8361 - I see you are out for a while.  I am merging this to unblock CI.  We can iterate on this when you return if you have other suggestions.

**Comment by mikem8361** [comment]
I think removing lldb-dev this may break coreclr repo builds when building the lldb plugin.  Do we still build coreclr on alpine 3.6? 

What is the alpine docker image path/name with this change? I can try building coreclr myself.

**Comment by wfurt** [comment]
If needed, I think we can drop 3.6 support and do only 3.8 and 3.9 as last stable versions.

**Comment by MichaelSimons** [comment]
@mikem8361 - please try this image `mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.6-9a37eff-20190415134749`

**Comment by mikem8361** [comment]
The coreclr repo can no longer build with this alpine docker image. Eventually, the SOS and the lldb plugin will be removed from coreclr and be built/distributed from the diagnostics repo, but I don't have a good time frame when this will be ready.

We could also make a change to coreclr to make building the plugin optional.

```
-- LLDB_LIB:
CMake Error at src/ToolBox/SOS/lldbplugin/CMakeLists.txt:120 (message):
  Cannot find LLDB.h Try installing lldb-3.9-dev (or the appropriate package
  for your platform).  You may need to set LLVM_HOME or LLDB_INCLUDE_DIR if
  the build still can't find it.


-- Configuring incomplete, errors occurred!

```

**Pull request merged**
