### PR TITLE
Delete Fedora rawhide Dockerfile

### PR DESCRIPTION
**Pull request by mthalman**
Deleting this because the image isn't being consumed and we're having issues with getting it built (https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/484).  It's already been removed from the manifest by https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/486.

### CODE REVIEW

**Comment by wfurt** [comment]
Looks good to me. I'm not sure what was original idea when @omajid put it in. 
Keeping images updated is tedious but we seems to get better at it.

**Comment by crummel** [comment]
We were planning to start running source-build CI on rawhide (this would have caught a couple issues a lot earlier than we actually run into them), but we haven't had the time yet to actually spin it up.

**Review by crummel — APPROVED** [review]
LGTM but we'll probably want to bring this back eventually.

**Comment by omajid** [comment]
> I'm not sure what was original idea when @omajid put it in.

Basically, rawhide represents the next release of Fedora (and in some cases, RHEL). So making sure rawhide works is a great way to make sure .NET will work with upcoming versions of Fedora and RHEL.

> Deleting this because the image isn't being consumed and we're having issues with getting it built (#484). 

FWIW, from what I am hearing, the build failure is caused by a "feature" and there is no plan to revert it. When Fedora 35 is released it will have the same issue. The maintainers are still telling me that the fix needs to go into the docker tool being used to build the images.

**Comment by wfurt** [comment]
does it mean we should update the image builder it self? 
And if you know @omajid, what would be first distro with OpenSSL 3.0 as a base? 
That would certainly be interesting to test early as crap is likely to happen.

**Comment by omajid** [comment]
> does it mean we should update the image builder it self?

Yes. From what I can tell, `moby`/`docker`itself, or [the seccomp filters](https://docs.docker.com/engine/security/seccomp/) need to be fixed here. On that note, any chance you can find someone at Microsoft who would know more about what it would take to update the image builders used by Github Actions/Azure DevOps?

>  And if you know @omajid, what would be first distro with OpenSSL 3.0 as a base?

I know many distributions are evaluating it but not sure any distributions that might be released soon have already switched yet.

I know RHEL 9 is planning to use OpenSSL 3.0 as the base, but I don't expect that to be released for another year or so. The nightly builds for it have OpenSSL 3.0 beta:

```
$ docker run -it quay.io/centos/centos:stream9-development dnf info openssl
UNSIGNED CentOS Stream 9 BaseOS                                                       390 kB/s | 918 kB     00:02    
UNSIGNED CentOS Stream 9 AppStream                                                    2.8 MB/s | 5.4 MB     00:01    
Last metadata expiration check: 0:00:01 ago on Wed Jul 28 20:25:27 2021.
Available Packages
Name         : openssl
Epoch        : 1
Version      : 3.0.0
Release      : 0.beta1.4.el9
Architecture : x86_64
Size         : 1.1 M
Source       : openssl-3.0.0-0.beta1.4.el9.src.rpm
Repository   : baseos
Summary      : Utilities from the general purpose cryptography library with TLS implementation
URL          : http://www.openssl.org/
License      : ASL 2.0
Description  : The OpenSSL toolkit provides support for secure communications between
             : machines. OpenSSL includes a certificate management tool and shared
             : libraries which provide various cryptographic algorithms and
             : protocols.
```

**Comment by MichaelSimons** [comment]
> > does it mean we should update the image builder it self?
> 
> Yes. From what I can tell, moby/dockeritself, or the seccomp filters need to be fixed here. On that note, any chance you can find someone at Microsoft who would know more about what it would take to update the image builders used by Github Actions/Azure DevOps?

Trying to provide clarity here on how I am interpreting this situation.  The `image builder` tool used by this repo is a tool used by the .NET team to orchestrate our Docker builds.  The tool is based on the `Docker` cli.  As @omajid indicates, the fix is needed in the moby/docker layer not our `image builder` tool.

**Review by MichaelSimons — APPROVED** [review]

**Pull request merged**
