### PR TITLE
Adding tzdata to fix Globalization tests

### PR DESCRIPTION
**Pull request by joperezr**
cc: @MichaelSimons @tarekgh

Adding dependency tzdata in order to fix the failing Globalization tests.

### CODE REVIEW

**Comment by joperezr** [comment]
@MichaelSimons is there a build I can kick off once this thing is merged in order to get the new image generated.

**Comment by MichaelSimons** [comment]
@joperezr - see https://github.com/dotnet/core-eng/blob/master/Documentation/Updating-Official-Build-Dockerfiles.md.  Please queue with the `imageBuilder.Path` variable set to src/alpine/3.6-ForHelix in order to avoid building Dockerfiles that have not changed (e.g. pushing identical images).  You will also need to remove `--dry-run` from the `imageBuilder.buildArgs` variable.

**Comment by joperezr** [comment]
cool, thanks for the info.

**Comment by MichaelSimons** [comment]
The following image was built as a result of this PR:
microsoft/dotnet-buildtools-prereqs:alpine-3.6-ForHelix-36109c1-20180320203700

**Pull request merged**
